# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
    - name: install dependencies
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: npm ci
    - name: build and deploy
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        npm run build
        cd dist
        git init
        git config --global user.email "<>" && git config --global user.name "Build Pipeline"
        git add .
        git commit -m "deploy"
        git push -f git@github.com:Treee/tech-widget-overlay.git master:gh-pages
